{{- if .Values.config.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  {{- if .Values.config.secret.databaseURI }}
  DATABASE_URI: {{ .Values.config.secret.databaseURI | b64enc }}
  {{- end }}
{{- end }}
